### ISSUE TITLE
Ready to be used (and also uploaded to Packagist)?

### ISSUE THREAD

**Issue by mikesoule** [pmjones/AutoShell#11]
@pmjones This looks fantastic and I'd like to use this in a couple projects. Would you say it's ready for real-world use? If so, do you have plans to make it available on Packagist soon?

**Comment by pmjones** [comment]
@mikesoule Thanks for saying! I'd say it's ready-ish, in that I have used it in some personal/local projects, but not on anything I'm getting paid for yet.

I'm happy to make a release to Packagist, but I think the responsible thing to do would be 1.0.0-alpha (not stable) release. That at least would expose it to real-world use, without making promises I might not be able to keep.

Would that be sufficient for your purposes?

**Comment by mikesoule** [comment]
@pmjones Sounds good!

**Comment by pmjones** [comment]
Here you go: https://packagist.org/packages/pmjones/auto-shell

It's 0.1.0-alpha, not 1.0.0 like the docs say :-/

Let me know if you have problems!

**Comment by mikesoule** [comment]
Thanks @pmjones!

**Comment by pmjones** [comment]
@mikesoule How is this package working out for you?

**Comment by mikesoule** [comment]
@pmjones It's working great. I was previously using [GetOpt.php](http://getopt-php.github.io/getopt-php/) but after replacing it with AutoShell I was able to just delete a bunch of unnecessary code. Right now I'm using it in a container that runs in several Kubernetes CronJobs to handle some long-running ETL processes and have had no issues so far.

I still need to buffer my outputs to remove annoyances like output being written in the midst of unit tests. Would love to see how others have solved the problem. Any recommendations on using built-in output buffering vs a shutdown handler or just a class with a `__destruct` method?

**Comment by pmjones** [comment]
> I still need to buffer my outputs to remove annoyances like output being written in the midst of unit tests. Would love to see how others have solved the problem. Any recommendations on using built-in output buffering vs a shutdown handler or just a class with a __destruct method?

What I do is avoid echo/print/etc. statements in the commands, and instead use a logger. I configure the logger to write to STDOUT in prod, and write to php://memory in tests. That allows me to read from memory during tests if i need to, and suppresses output otherwise. Cf. https://github.com/pmjones/stdlog

Does that help?
