### ISSUE TITLE
Replace direct output with a logger

### ISSUE THREAD

**Issue by compwright** [pmjones/AutoShell#6]
This can be optional if you want, but many implementations are going to want to format, write to multiple output streams, or otherwise control the output.

Console::new() needs to accept an (optional?) LoggerInterface and write to it rather than writing directly to `STDOUT` or `STDERR`.

**Comment by pmjones** [comment]
/me nods along

... hm, let me walk through this ...

First,  AutoShell users creating CLI command classes get to use whatever they like for input/output; it's their command class, they can use STDOUT, a Logger implementation, a subject/observer notifier subsystem, or anything else.

Now, the Console only cares about output streams for two reasons: for the HelpCommand classes to output help text, and for CLI error output at invocation time.

The HelpCommand classes expect to send some output, and that to STDOUT by default. I have a hard time imagining cases where you would want a HelpCommand invoked at the command line to output anywhere else, except in testing, in which case it's easy to inject a different stream to the HelpCommand.

As for Console error reporting at invocation time, there *might* be a case for non-stream alternatives? I can imagine, say, a cron job hitting an AutoShell Console, and the cron command is specified incorrectly. In that case, the error will go to STDERR, which is what I'd expect. Is there some other case where you'd want the invocation-time error reporting to go anywhere other than STDERR? (Again, you'd want that in testing -- but again, you can inject a different stream there.)

What am I missing?

**Comment by compwright** [comment]
Agreed re: help output.

On error output, it is vital to be able to control whether, how, and where
the error is reported. In real life scenarios this is important for use
with notification services. There are also plenty of use cases that need
verbosity set to none, so that there is no output to the console.

Sent via Superhuman iOS ***@***.***>

**Comment by pmjones** [comment]
[68a1a81](https://github.com/pmjones/AutoShell/commit/68a1a81fc2f95ab4956343a86b7a9d81e4db46b7) replaces $stdout/$stderr resources with callables, which should be enough for any potential use case at this outermost layer.
